gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc@12
  unify: true
  specs:
  - cuda@12
  - fmt
  - pugixml
  - nlohmann-json
  - random123
  - python@3.10
  - py-numpy
  - py-pybind11
  - py-sphinx
  - py-svgwrite
  - py-pip
  - cmake
  - ninja
  variants:
  - +cuda
  - cuda_arch=80
  views:
    default:
      link: run
  packages:
  - git
  - perl
  - diffutils
  - gettext

